name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@0dcf370eb08b3f884992181348b8c41d7f66c10e # main
        with:
          repository: openstack/designate
          ref: 5468f686779409bf2c842738d48e155c6aaf83d5 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@0dcf370eb08b3f884992181348b8c41d7f66c10e # main
        with:
          image-name: designate
          build-contexts: designate=openstack/designate
          push: ${{ github.event_name != 'pull_request' }}
